-- ============================================================================
-- V14: Employee soft-delete + break ON DELETE CASCADE to preserve audit history.
--
-- Problem: sys_employees.user_id has ON DELETE CASCADE, meaning a hard-delete
-- of sys_users would silently wipe the employee record and break all audit
-- trail references. sys_users uses Hibernate @SQLDelete (UPDATE SET deleted_at),
-- so Hibernate-triggered deletes never fire the cascade; but raw SQL or future
-- tooling could. This migration:
--   1. Adds offboarding columns (soft-delete fields).
--   2. Replaces CASCADE with RESTRICT so a direct DELETE on sys_users is
--      blocked unless the employee row is removed first — a deliberate gate.
-- ============================================================================

-- 1. Soft-delete columns
ALTER TABLE sys_employees
    ADD COLUMN IF NOT EXISTS offboarded_at    TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS offboarded_by    UUID,
    ADD COLUMN IF NOT EXISTS offboard_reason  VARCHAR(500);

-- 2. Replace ON DELETE CASCADE with ON DELETE RESTRICT.
--    The FK name generated by V0 follows PostgreSQL's default naming convention.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'sys_employees_user_id_fkey'
          AND table_name      = 'sys_employees'
    ) THEN
        ALTER TABLE sys_employees
            DROP CONSTRAINT sys_employees_user_id_fkey;
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'sys_employees_user_id_fkey_restrict'
          AND table_name      = 'sys_employees'
    ) THEN
        ALTER TABLE sys_employees
            ADD CONSTRAINT sys_employees_user_id_fkey_restrict
            FOREIGN KEY (user_id)
            REFERENCES sys_users (id)
            ON DELETE RESTRICT;
    END IF;
END $$;

-- 3. Partial index: fast lookup of active employees (offboarded_at IS NULL).
CREATE INDEX IF NOT EXISTS idx_sys_employees_active
    ON sys_employees (user_id)
    WHERE offboarded_at IS NULL;

-- 4. Index for historical/offboarded queries.
CREATE INDEX IF NOT EXISTS idx_sys_employees_offboarded_at
    ON sys_employees (offboarded_at DESC NULLS LAST)
    WHERE offboarded_at IS NOT NULL;
