import { jsPDF } from 'jspdf'
import type { VoucherDto } from '../../types/api'

function fmt(dateStr: string): string {
  try { return new Date(dateStr).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }) }
  catch { return dateStr }
}

export function downloadVoucherPdf(voucher: VoucherDto): void {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const W = doc.internal.pageSize.getWidth()
  let y = 20

  // Header bar
  doc.setFillColor(26, 60, 45)
  doc.rect(0, 0, W, 18, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Ziyara', 14, 12)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  doc.text('Booking Voucher', W - 14, 12, { align: 'right' })

  y = 32
  // Reference box
  doc.setTextColor(26, 60, 45)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.text('Booking Reference', 14, y)
  y += 7
  doc.setFontSize(22)
  doc.setFont('helvetica', 'bold')
  doc.text(voucher.bookingReference, 14, y)

  y += 14
  doc.setDrawColor(220, 220, 220)
  doc.line(14, y, W - 14, y)
  y += 8

  const row = (label: string, value: string) => {
    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(120, 120, 120)
    doc.text(label.toUpperCase(), 14, y)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    doc.text(value, 14, y + 5)
    y += 14
  }

  row('Service', voucher.serviceName)
  row('Check-in', fmt(voucher.checkInDate))
  row('Check-out', fmt(voucher.checkOutDate))
  row('Guest email', voucher.customerEmail)
  row('Total', `${voucher.currency} ${Number(voucher.totalAmount).toFixed(2)}`)

  y += 4
  doc.line(14, y, W - 14, y)
  y += 8
  doc.setFontSize(8)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor(150, 150, 150)
  doc.text('Present this voucher at check-in. Generated by Ziyara.', 14, y)

  doc.save(`Ziyara-Voucher-${voucher.bookingReference}.pdf`)
}
